services:

  anonchat-telegram:
    build:
      context: .
    restart: on-failure
    container_name: anonbot-tg
    volumes:
      - .:/app
    working_dir: /app 
    command: /venv/bin/python src/__main__.py

  mongo:
    image: mongo
    restart: on-failure
    container_name: mongo-anonbot-tg
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /var/lib/mongo:/data/db/
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 27017

  mongo-express:
    image: mongo-express
    restart: on-failure 
    container_name: mongo-express-anonbot-tg
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}